image: maven:3.3.9-jdk-8

stages:
  - build
  - release

before_script:
  #  - echo `pwd` # debug
  #  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - rm -f  .gradle/caches/modules-2/modules-2.lock
  - rm -fr .gradle/caches/*/plugin-resolution/

# Docker Dind fix (https://gitlab.com/gitlab-org/gitlab-runner/issues/4501#note_194648457)
variables:
  DOCKER_TLS_CERTDIR: ""

# Cache downloaded dependencies and plugins between builds.
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
    - build/libs/

build:
  stage: build
  script:
    - './gradlew clean'
    - './gradlew shadowJar'
  artifacts:
    expire_in: 1 week
    paths:
      - build/libs/*.jar

release:tag:
  stage: release
  only:
    - master
  when: manual
  allow_failure: false
  before_script: []
  image: node:10
  script:
    - npm install -g auto-changelog
    - export RELEASE_VERSION=`cat build.gradle | grep "def mainVersion" | cut -c 19- | cut -c2- | rev | cut -c2-`
    - git config user.email "$GITLAB_USER_EMAIL"
    - git config user.name "$GITLAB_USER_EMAIL"
    - auto-changelog --template keepachangelog --package --commit-limit false
    - git commit -m "Release v$RELEASE_VERSION" -a
    - git push "https://${GIT_CI_USER}:${GIT_CI_PASS}@${CI_REPOSITORY_URL#*@}" "HEAD:master"
    - git tag v${RELEASE_VERSION} -a -m "$(git log --pretty="%s" `git describe --abbrev=0 --tags`...HEAD)"
    - git push "https://${GIT_CI_USER}:${GIT_CI_PASS}@${CI_REPOSITORY_URL#*@}" --tags

release:docker:
  image: $CI_REGISTRY/craftmania/docker/java8-docker:latest
  stage: release
  services:
    - docker:dind
  tags:
    - privileged
  dependencies:
    - build
  only:
    - tags
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_PIPELINE_ID" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_PIPELINE_ID"
    - docker tag "$CI_REGISTRY_IMAGE:$CI_PIPELINE_ID" "$CI_REGISTRY_IMAGE:stable"
    - docker push "$CI_REGISTRY_IMAGE:stable"