image: maven:3.3.9-jdk-8

stages:
  - build
  - deploy

before_script:
  #  - echo `pwd` # debug
  #  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - rm -f  .gradle/caches/modules-2/modules-2.lock
  - rm -fr .gradle/caches/*/plugin-resolution/

# Cache downloaded dependencies and plugins between builds.
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
    - build/libs/

build:
  stage: build
  script:
    - './gradlew clean'
    - './gradlew shadowJar'
  artifacts:
    expire_in: 1 week
    paths:
      - build/libs/*.jar

registry:
  image: $CI_REGISTRY/craftmania/docker/java8-docker:latest
  stage: deploy
  services:
    - docker:dind
  tags:
    - privileged
  dependencies:
    - build
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_PIPELINE_ID" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_PIPELINE_ID"
    - docker tag "$CI_REGISTRY_IMAGE:$CI_PIPELINE_ID" "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:latest"