version: "3"
services:
  bot:
    image: git.craftmania.cz:4567/craftmania/sussi:stable
    restart: always
    network_mode: "host"
    user: root
    container_name: sussibot
    volumes:
      - /srv/sussi/config.yml:/srv/config.yml
      - /srv/sussi/logs:/srv/logs
    stop_grace_period: 7200s
    entrypoint:
      - java
      - -jar
      - -Xmx1g
      - -XX:+UseG1GC
      - -XX:+ParallelRefProcEnabled
      - -XX:+UseStringDeduplication
      - Sussi.jar