# Pri prvnim spusteni je potreba tento soubor prejmenovat na config.yml!

# Napojeni na SQL
hostname: host
port: 3306
database: database
username: user
password: password

# Nastaveni SQL
minimumConnections: 2
maximumConnections: 5
timeout: 30000

# Discord Token
token: token-from-discord-api

# IPHub Key
ipHubKey: keys
proxycheckKey: kek

# Beta
isBeta: true

# Prometheus Stats
metrics:
  enabled: false

# Integrace s Dialogglow
dialogflow-enabled: true
dialogflow-api-key: some-key-yep
dialogflow-channels: "kek", "kek"

# IDs
cm_guild: 207412074224025600
navrhy_diskuze: 648576105619521537
navrhy_hlasovani: 651205289894215728
owner: 177516608778928129
at_pokec: 236749682229903360
secret_channel_ats: 694263824584540211
oznameni: 292439916493930496

# CraftBox
adminKey: ''