# Pri prvnim spusteni je potreba tento soubor prejmenovat na config.yml!

# Napojeni na SQL
hostname: host
port: 3306
database: database
username: user
password: password

# Nastaveni SQL
minimumConnections: 2
maximumConnections: 5
timeout: 30000

# Discord Token
token: token-from-discord-api

# IPHub Key
ipHubKey: keys
proxycheckKey: kek

# Beta
isBeta: true

# Prometheus Stats
metrics:
  enabled: false

# Integrace s Dialogglow
dialogflow-enabled: true
dialogflow-api-key: some-key-yep
dialogflow-channels: "kek", "kek"