name: Build Master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build bot
        run: ./gradlew shadowJar
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Artifacts
          path: build/libs

  packages:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: Artifacts
          path: build/libs

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT_CONTAINER_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          push: true
          file: ./Dockerfile
          tags: |
            ghcr.io/craftmania-cz/sussi:${{ github.run_id }}
            ghcr.io/craftmania-cz/sussi:master
            ghcr.io/craftmania-cz/sussi:latest