name: Build Develop

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Build bot
        run: ./gradlew shadowJar
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Artifacts
          path: build/libs